// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using system_metrics.Infrastructure.Persistence;

#nullable disable

namespace system_metrics.Infrastructure.Migrations
{
    [DbContext(typeof(SystemMetricsDBContext))]
    [Migration("20260127180609_MakePropertiesNullableWithRequired")]
    partial class MakePropertiesNullableWithRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("system_metrics.Domain.Entities.DeviceDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BatteryLevel")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MemoryUsage")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThermalValue")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
